#!/bin/sh

# exit on error
set -e

if ! command -v sudo &> /dev/null; then
  SUDO='' # sudo doesn't exist
else
  SUDO='sudo LD_LIBRARY_PATH=$LD_LIBRARY_PATH'
fi

cd ~

# pre-create some directories
#${SUDO} mkdir -p /usr/GNUstep/Local/Library/Libraries
#${SUDO} mkdir -p /usr/GNUstep/Local/Library/Headers

# cleanup
${SUDO} rm -rf libdispatch
${SUDO} rm -rf libobjc2
   
# pull
git clone --recursive https://github.com/gnustep/libobjc2.git
git clone --recursive https://github.com/nickhutchinson/libdispatch.git

# set vars
export CC=clang
export CXX=clang++

# build and install
cd libdispatch
rm -rf libdispatch-build
mkdir libdispatch-build && cd libdispatch-build
../configure
make
${SUDO} make install
${SUDO} ldconfig

cd ~/libobjc2
mkdir libobjc2-build && cd libobjc2-build
cmake ../
cmake --build . --target install
${SUDO} -E make install
${SUDO} ldconfig


